package com.projecteuler.problem2;

/**
 * Programa que resuelve el problema 2 de projecteuler.net
 * A continuacion se muestra la descripcion del problema
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * @author armando
 */
public class Problem2 {
    public static void main(String[] args) {
        System.out.println(getSumaFibo(4000000));
    }
    
    public static long getSumaFibo(long numeroMaximo){
        long resultado=0, numFibo;
        boolean salir = false;
        int i=1;
        while(salir==false){
            numFibo = fibonacci(i++);
            if(numFibo<numeroMaximo){
                if(esNumeroPar(numFibo))
                    resultado += numFibo;
            }else
                salir = true;            
        }
        return resultado;
    }
    
    public static boolean esNumeroPar(long numero){
        return numero%2==0 ? true:false;
    }
    
    public static long fibonacci(int numero) {
        if (numero < 2) 
            return numero;
        else return fibonacci(numero-1) + fibonacci(numero-2);
    }
}
